title: "{{HOMEPAGE_VAR_title}}"

background:
    image: /images/bruh.jpg
    saturate: 0
    brightness: 50
    opacity: 100

headerStyle: boxed
theme: dark
color: slate

language: en

useEqualHeights: true

target: _blank

hideVersion: true

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: false
    showSearchSuggestions: true
    hideVisitURL: true

layout:
    ##### HTTPS #####
    Machines:
        tab: HTTPS ðŸ”’
        style: row
        columns: 4
    Networking:
        tab: HTTPS ðŸ”’
        style: row
        columns: 3
    Crypto & Finance:
        tab: HTTPS ðŸ”’
        style: row
        columns: 3
        useEqualHeights: false
    Files & Pictures:
        tab: HTTPS ðŸ”’
        style: row
        columns: 3
        useEqualHeights: false
    # Stuff:
    #     tab: HTTPS ðŸ”’
    #     style: row
    #     columns: 1
    Minecraft Admin:
        tab: HTTPS ðŸ”’
        style: row
        columns: 3
        useEqualHeights: false
    Minecraft Servers:
        tab: HTTPS ðŸ”’
        style: row
        columns: 2
    ##### HTTP #####
    _Machines:
        tab: HTTP ðŸ”“
        style: row
        columns: 4
    _Networking:
        tab: HTTP ðŸ”“
        style: row
        columns: 3
    _Crypto & Finance:
        tab: HTTP ðŸ”“
        style: row
        columns: 3
        useEqualHeights: false
    _Files & Pictures:
        tab: HTTP ðŸ”“
        style: row
        columns: 3
        useEqualHeights: false
    # _Stuff:
    #     tab: HTTP ðŸ”“
    #     style: row
    #     columns: 1
    _Minecraft Admin:
        tab: HTTP ðŸ”“
        style: row
        columns: 3
        useEqualHeights: false
    _Minecraft Servers:
        tab: HTTP ðŸ”“
        style: row
        columns: 2
